# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: shannonfuzz_mongodb_fzy #docker容器的名字
    restart: always
    ports: #容器运行的端口号和对应的容器内部的端口号
      - "27017:27017"
    volumes: # 数据持久化
      - mongodb-share:/data/db/
      - ./mongodb/log/:/var/log/mongodb
    command: [ --auth ] # 指定需要认证，mongdb默认是无认证的
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: shannonfuzz
      MONGO_USERNAME: aidpaike
      MONGO_PASSWORD: 123456
      TZ: Asia/Shanghai

  mongo-express:
    image: mongo-express
    container_name: shannonfuzz_mongo_express_fzy #docker容器的名字
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: "mongodb://admin:123456@mongo:27017/"

volumes:
  mongodb-share: